### ISSUE TITLE
Chrome: It looks like  your browser is not supported

### ISSUE THREAD

**Issue by juanca** [sonm-io/Wallet#24]
Version 63.0.3239.84 (Official Build) (64-bit)

---

Downloaded the zip and opened the `index.html`. 

Here is the stack trace:

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new <anonymous> (file:///Users/juanca/Documents/sonm-wallet-v0.1.6/app.bundled.js:1:2205333)
    at Object.<anonymous> (file:///Users/juanca/Documents/sonm-wallet-v0.1.6/app.bundled.js:1:2205296)
    at t (file:///Users/juanca/Documents/sonm-wallet-v0.1.6/app.bundled.js:1:101)
    at Object.<anonymous> (file:///Users/juanca/Documents/sonm-wallet-v0.1.6/app.bundled.js:1:1244931)
    at t (file:///Users/juanca/Documents/sonm-wallet-v0.1.6/app.bundled.js:1:101)
    at Object.<anonymous> (file:///Users/juanca/Documents/sonm-wallet-v0.1.6/app.bundled.js:1:713199)
    at t (file:///Users/juanca/Documents/sonm-wallet-v0.1.6/app.bundled.js:1:101)
    at Object.<anonymous> (file:///Users/juanca/Documents/sonm-wallet-v0.1.6/app.bundled.js:1:845899)
    at t (file:///Users/juanca/Documents/sonm-wallet-v0.1.6/app.bundled.js:1:101)
    at Object.<anonymous> (file:///Users/juanca/Documents/sonm-wallet-v0.1.6/app.bundled.js:1:966510)
```

**Comment by dmitrypisanko** [comment]
Try to disable "Block third-party cookies"

Chrome Settings -> Advanced -> Content Settings -> Cookies -> Block third-party cookies
